### Request Users
GET http://localhost:3003/api/users

### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "minhnd01",
  "name": "Duc Minh",
  "password": "12345678"
}

### Create an invalid user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "minhnd03",
  "password": "123"
}

### Delete a user
DELETE http://localhost:3003/api/users/63adfe6e7b40f0f1814541a5

### Update a user
PUT http://localhost:3003/api/users/63adff4310c9fdb614e76602
Content-Type: application/json

{
  "username": "minhnd03",
  "name": "Duc Minh Nguyen",
  "password": "1234567890"
}